//using System;

//class Program
//{
//    static void Main(string[] args)
//    {
//        try
//        {
//            int a = 10, b = 0;
//            int c = a / b; // This line will throw a DivideByZeroException
//        }
//        catch (DivideByZeroException ex)
//        {
//            Console.WriteLine("Caught exception: " + ex.Message);
//        }
//        finally
//        {
//            Console.WriteLine("Finally block executed.");
//        }

//        Console.WriteLine("Program completed successfully.");
//        Console.ReadLine();
//    }
//}
